### ISSUE TITLE
Can't found NDISAPI.dll

### ISSUE THREAD

**Issue by SuperTiger-ops** [wiresock/ndisapi.net#8]
When start debug, vs can't found ndisapi.dll, where can found it.

**Comment by wiresock** [comment]
The entire source code for ndisapi.dll can be accessed at [this GitHub link](https://github.com/wiresock/ndisapi). For those who opt for pre-compiled binaries, they are included in the binary sample packages, which are available in the [releases section](https://github.com/wiresock/ndisapi/releases/tag/v3.4.3) of the repository. Additionally, it's important to download and install the Windows Packet Filter driver, which can be found at the same link.
